spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wag?serverTimezone=Asia/Seoul
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
  packages-to-scan: com.kkw.pawket
  paths-to-match: /**

app:
  backend-url: http://localhost:8080
  oauth:
    google:
      client-id: YOUR_GOOGLE_CLIENT_ID
      client-secret: YOUR_GOOGLE_CLIENT_SECRET
      redirect-uri: "{app.backend-url}/oauth2/callback/google"
      scope: profile, email
    kakao:
      client-id: YOUR_KAKAO_CLIENT_ID
      client-secret: YOUR_KAKAO_CLIENT_SECRET
      redirect-uri: "{app.backend-url}/oauth2/callback/kakao"
      scope: profile_nickname, profile_image, account_email
    apple:
      client-id: YOUR_APPLE_CLIENT_ID
      client-secret: YOUR_APPLE_CLIENT_SECRET
      redirect-uri: "{app.backend-url}/oauth2/callback/apple"
      scope: name, email

jwt:
  secret-key: v0V/lOYb8nyCfM298Cai1q/BLARsBg+hLFZld4yWbL3KmRQb7cNN7fsrnSwpeQ2PtyNm+GyCiq+jS0TdUTZQsQ==
  validity-in-milliseconds: 36000000

cloud:
  aws:
      credentials:
        access-key: 
        secret-key: 
      s3:
        bucket:
          name: wag-s3
          region: ap-northeast-2
        url-prefix:
          image: https://s3.ap-northeast-2.amazonaws.com/wag/upload/image/
          dogs: https://s3.ap-northeast-2.amazonaws.com/wag/upload/dogs/

clova-ai:
    open-api:
        key: nv-c9cd13ac4f42478f9f471e532d9752f7zMq9
        base-url: https://clovastudio.stream.ntruss.com/

oss:
  base-url: http://localhost:8080/v1
  chat-path: /chat/completions
  model: gpt-oss-20b
