spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:mysql://localhost:3306/dog_walker
    username: pet
    password: pet
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: profile, email
          kakao:
            client-id: YOUR_KAKAO_CLIENT_ID
            client-secret: YOUR_KAKAO_CLIENT_SECRET
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/callback/kakao"
            scope: profile_nickname, profile_image, account_email
          apple:
            client-id: YOUR_APPLE_CLIENT_ID
            client-secret: YOUR_APPLE_CLIENT_SECRET
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/oauth2/callback/apple"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
jwt:
  secret-key: your-jwt-secret
  validity-in-milliseconds: 36000000