spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:mysql://localhost:3306/wag
    username: wag
    password: wag
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo
app:
  backend-url: http://localhost:8080
  oauth:
    google:
      client-id: YOUR_GOOGLE_CLIENT_ID
      client-secret: YOUR_GOOGLE_CLIENT_SECRET
      redirect-uri: "{baseUrl}/oauth2/callback/google"
      scope: profile, email
    kakao:
      client-id: YOUR_KAKAO_CLIENT_ID
      client-secret: YOUR_KAKAO_CLIENT_SECRET
      redirect-uri: "{baseUrl}/oauth2/callback/kakao"
      scope: profile_nickname, profile_image, account_email
    apple:
      client-id: YOUR_APPLE_CLIENT_ID
      client-secret: YOUR_APPLE_CLIENT_SECRET
      redirect-uri: "{baseUrl}/oauth2/callback/apple"

jwt:
  secret-key: your-jwt-secret
  validity-in-milliseconds: 36000000

cloud:
  aws:
      s3:
        credentials:
          access-key: YOUR_AWS_ACCESS_KEY
          secret-key: YOUR_AWS_SECRET_KEY